import { Inter } from "next/font/google";

import "./globals.scss";
import BootstrapInit from "@/elements/BootstrapInit";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapInit />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
